### ISSUE TITLE
IAsyncEnumerable pipeline stalling when there is a data error

### ISSUE THREAD

**Issue by lee-baker** [jbogard/bulk-writer#87]
I have come across an issue where when I am inputting data via an IAsyncEnumerable, that throws an exception because of bad data, that exception doesn't get raised in the calling code.
I can see in the "EtlPipelineStep.cs" Run method you have a finally that completes adding to the output collection with a comment about how it is supposed to prevent the stalled pipeline but I think I have a case where that doesn't actually happen.

I am using the pipeline because it allows me to read ahead of the sql writes, which I think speeds up the writing to sql, however I am not using any of the other pipeline features.

I have found that when my data to be inserted is less than the batch size the exception gets raised correctly however when I get a file that has more records than the batch the exception does not get raised and the batch insert seems to stall. 

When using the standard BulkWriter WriteToDatabaseAsync method it all works as expected.

**Comment by bptillman** [comment]
@lee-baker Thanks for bringing this issue to our attention. Would you be able to provide a fork or code example that replicates this issue? We will take a look at this as time permits, and as always, pull requests are welcome.
